const questions=[
{title:"Что такое аномалия?",text:"ИИ заметил событие, которое отличается от обычного поведения игрока. Как это называется?",answers:["Аномалия","Пароль","Серверная","Сундук"],correct:0,explain:"Аномалия — это необычное событие, которое нужно проверить."},
{title:"Обычное или подозрительное?",text:"Игрок зашёл днём, построил дом, сложил ресурсы в свой сундук и играл 40 минут.",answers:["Это обычное поведение","Это точно взлом","Это фишинг","Это вирус"],correct:0,explain:"Поведение похоже на обычную игру."},
{title:"Где больше риска?",text:"Игрок зашёл в 03:12, разрушил башню, открыл чужие сундуки и вышел через 2 минуты.",answers:["Обычное событие","Аномалия","Надёжный источник","Резервная копия"],correct:1,explain:"Несколько подозрительных действий подряд — повод для проверки."},
{title:"Может ли ИИ ошибаться?",text:"ИИ отметил действия как подозрительные. Что должен сделать агент?",answers:["Сразу наказать игрока","Удалить сервер","Проверить факты и контекст","Никому не рассказывать"],correct:2,explain:"ИИ помогает, но решение принимает человек."},
{title:"Сообщение от админа",text:"Игрок получил сообщение: «Я администратор. Для проверки аккаунта отправь пароль». Что делать?",answers:["Отправить пароль","Попросить друга отправить пароль","Не отправлять пароль и сообщить взрослому/администратору","Ответить случайным паролем"],correct:2,explain:"Пароль нельзя сообщать никому."},
{title:"Главный секрет",text:"Что из этого нельзя передавать другим людям?",answers:["Никнейм","Любимый блок","Пароль","Название базы"],correct:2,explain:"Пароль — это секрет."},
{title:"Подозрительный приз",text:"Сообщение обещает 10000 MineCoin и просит перейти на неизвестный сайт. Что это может быть?",answers:["Фишинг","Обычная новость","Комната тревоги","Строительный план"],correct:0,explain:"Слишком щедрый приз и неизвестная ссылка — признаки фишинга."},
{title:"Что умеет ИИ?",text:"Как ИИ помогает агентам СМАРТ?",answers:["Читает мысли","Ищет подозрительные события и сообщения","Всегда знает правду","Принимает решения за человека"],correct:1,explain:"ИИ ищет необычное и помогает анализировать."},
{title:"Команда безопасности",text:"Какая команда работает лучше всего?",answers:["Только ИИ","Только робот","Человек + ИИ","Только случай"],correct:2,explain:"ИИ даёт подсказки, а человек проверяет и принимает решение."},
{title:"Центр кибербезопасности",text:"Что логично добавить в защищённый штаб Minecraft?",answers:["Центр мониторинга, серверную ИИ и хранилище данных","Только бассейн","Только ферму пшеницы","Только комнату с тортами"],correct:0,explain:"Эти комнаты помогают защищать сервер и данные."}
];
let index=0,score=0,studentName="";
const $=s=>document.querySelector(s);const startScreen=$("#startScreen"),quizScreen=$("#quizScreen"),resultScreen=$("#resultScreen"),startBtn=$("#startBtn"),studentNameInput=$("#studentName"),progressText=$("#progressText"),scoreText=$("#scoreText"),progressBar=$("#progressBar"),questionTitle=$("#questionTitle"),questionText=$("#questionText"),answersRoot=$("#answers"),feedback=$("#feedback"),nextBtn=$("#nextBtn"),finalScore=$("#finalScore"),resultTitle=$("#resultTitle"),resultMessage=$("#resultMessage"),retryBtn=$("#retryBtn"),copyBtn=$("#copyBtn"),saveBtn=$("#saveBtn"),copyStatus=$("#copyStatus");
function show(screen){[startScreen,quizScreen,resultScreen].forEach(s=>s.classList.remove("active"));screen.classList.add("active")}
function renderQuestion(){const q=questions[index];progressText.textContent=`Вопрос ${index+1} / ${questions.length}`;scoreText.textContent=`${score} баллов`;progressBar.style.width=`${index/questions.length*100}%`;questionTitle.textContent=q.title;questionText.textContent=q.text;feedback.classList.add("hidden");nextBtn.classList.add("hidden");answersRoot.innerHTML="";q.answers.forEach((answer,i)=>{const btn=document.createElement("button");btn.className="answer";btn.textContent=answer;btn.addEventListener("click",()=>chooseAnswer(i));answersRoot.appendChild(btn)})}
function chooseAnswer(answerIndex){const q=questions[index],buttons=[...document.querySelectorAll(".answer")];buttons.forEach(btn=>btn.classList.add("disabled"));if(answerIndex===q.correct){score++;buttons[answerIndex].classList.add("correct");feedback.innerHTML=`✅ <strong>Верно!</strong><br>${q.explain}`}else{buttons[answerIndex].classList.add("wrong");buttons[q.correct].classList.add("correct");feedback.innerHTML=`❌ <strong>Не совсем.</strong><br>${q.explain}`}scoreText.textContent=`${score} баллов`;feedback.classList.remove("hidden");nextBtn.classList.remove("hidden")}
function resultText(){return `Тест «Нейросеть на страже сети». ${studentName||"Агент"}: ${score}/${questions.length} баллов.`}
function finish(){progressBar.style.width="100%";show(resultScreen);finalScore.textContent=`${score} / ${questions.length}`;let level="",message="";if(score>=9){level="🛡️ Эксперт кибербезопасности";message="Отличная работа! Ты уверенно распознаёшь угрозы и умеешь проверять выводы ИИ."}else if(score>=7){level="🤖 Старший агент СМАРТ";message="Хороший результат! Ты понимаешь, как ИИ помогает защищать Minecraft-мир."}else if(score>=5){level="🔍 Агент-стажёр";message="Неплохо! Повтори признаки фишинга, аномалий и правила работы с паролями."}else{level="📚 Новобранец";message="Нужно потренироваться ещё раз. Пройди тест повторно и внимательно читай объяснения."}resultTitle.textContent=level;resultMessage.textContent=`${studentName?studentName+", ":""}${message}`}
startBtn.addEventListener("click",()=>{studentName=studentNameInput.value.trim();index=0;score=0;show(quizScreen);renderQuestion()});nextBtn.addEventListener("click",()=>{index++;index>=questions.length?finish():renderQuestion()});retryBtn.addEventListener("click",()=>{index=0;score=0;show(quizScreen);renderQuestion()});copyBtn.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(resultText());copyStatus.textContent="Результат скопирован!"}catch(e){copyStatus.textContent=resultText()}});saveBtn.addEventListener("click",()=>{const blob=new Blob([resultText()],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="result-smart-test.txt";a.click();URL.revokeObjectURL(a.href)});
